spring:
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: false
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:clientid}
      client-secret: ${CLIENT_SECRET:clientsecret}
jwt:
  secret: ${JWT_SECRET:jwtsecret}
  duration: ${JWT_DURATION:600}